const tasks = [
  {
    id: 1,
    title: "Hoàn thành bài tập React",
    description: "Làm xong phần CRUD trong React",
    priority: "Cao",
    category: "Học tập",
    dueDate: "2025-04-10",
    completed: false,
  },
  {
    id: 2,
    title: "Đọc sách về AI",
    description: "Hoàn thành chương 3 của sách 'Deep Learning cơ bản'",
    priority: "Trung bình",
    category: "Học tập",
    dueDate: "2025-04-15",
    completed: false,
  },
  {
    id: 3,
    title: "Tập gym",
    description: "Luyện tập sức mạnh cho phần thân trên",
    priority: "Thấp",
    category: "Sức khỏe",
    dueDate: "2025-04-05",
    completed: false,
  },
  {
    id: 4,
    title: "Viết báo cáo thực tập",
    description: "Hoàn thành phần kết luận cho báo cáo thực tập",
    priority: "Cao",
    category: "Công việc",
    dueDate: "2025-04-12",
    completed: false,
  },
  {
    id: 5,
    title: "Học tiếng Anh",
    description: "Ôn lại từ vựng và ngữ pháp về chủ đề công nghệ",
    priority: "Trung bình",
    category: "Học tập",
    dueDate: "2025-04-08",
    completed: false,
  },
  {
    id: 6,
    title: "Làm bài tập SQL",
    description: "Viết các truy vấn nâng cao với JOIN và GROUP BY",
    priority: "Cao",
    category: "Học tập",
    dueDate: "2025-04-07",
    completed: false,
  },
  {
    id: 7,
    title: "Dọn dẹp nhà cửa",
    description: "Lau sàn, quét bụi, sắp xếp lại bàn làm việc",
    priority: "Thấp",
    category: "Cá nhân",
    dueDate: "2025-04-06",
    completed: false,
  },
  {
    id: 8,
    title: "Đi siêu thị",
    description: "Mua thực phẩm cho cả tuần",
    priority: "Trung bình",
    category: "Cá nhân",
    dueDate: "2025-04-05",
    completed: false,
  },
  {
    id: 9,
    title: "Gửi email cho giảng viên",
    description: "Hỏi về nội dung bài giảng và bài tập nhóm",
    priority: "Cao",
    category: "Công việc",
    dueDate: "2025-04-09",
    completed: false,
  },
  {
    id: 10,
    title: "Xem tài liệu về hệ thống phân tán",
    description: "Đọc các bài báo khoa học về kiến trúc microservices",
    priority: "Trung bình",
    category: "Học tập",
    dueDate: "2025-04-14",
    completed: false,
  },
  ];
  
  export default tasks;
  